<a href="https://colab.research.google.com/github/gopalbansal24/Gopal/blob/master/Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Regression**

**Importing the Libraries**

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**Importing the Dataset**

In [0]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [4]:
print(x.shape)

(9568, 4)


In [5]:
print(y.shape)

(9568,)


**Splitting the dataset into training and testing set**

In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [11]:
print(np.concatenate((x_train.shape, x_test.shape, y_train.shape, y_test.shape)))

[7654    4 1914    4 7654 1914]


# Training Models

Multiple Linear Regression

In [12]:
from sklearn.linear_model import LinearRegression
lrm = LinearRegression()
lrm.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

Polynomial Regression

In [13]:
from sklearn.preprocessing import PolynomialFeatures
prm = PolynomialFeatures(degree=4)
x_poly = prm.fit_transform(x_train)
regressor = LinearRegression()
regressor.fit(x_poly,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

Decision Tree

In [0]:
from sklearn.tree import DecisionTreeRegressor
dtm = DecisionTreeRegressor(random_state=0)
dt = dtm.fit(x_train,y_train)

Random Forest Regression

In [0]:
from sklearn.ensemble import RandomForestRegressor
rfm = RandomForestRegressor(random_state=0,n_estimators=10)
rf = rfm.fit(x_train,y_train)

# Predicting Results

Multiple Regression

In [17]:
y_pred_lrm = lrm.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_lrm.reshape(len(y_pred_lrm),1), y_test.reshape(len(y_test),1)),1))

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


Polynomial Regression

In [20]:
y_pred_prm = regressor.predict(prm.transform(x_test))
print(np.concatenate((y_pred_prm.reshape(len(y_pred_prm),1), y_test.reshape(len(y_test),1)),1))

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.66 463.28]]


Decision Trees

In [31]:
y_pred_dtm = dtm.predict(x_test)
print(np.concatenate((y_pred_dtm.reshape(len(y_pred_dtm),1),y_test.reshape(len(y_test),1)),1))

[[431.28 431.23]
 [462.81 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.55 463.28]]


Random Forest

In [23]:
y_pred_rfm = rfm.predict(x_test)
print(np.concatenate((y_pred_rfm.reshape(len(y_pred_rfm),1),y_test.reshape(len(y_test),1)),1))

[[433.78 431.23]
 [457.99 460.01]
 [463.14 461.14]
 ...
 [470.16 473.26]
 [439.51 438.  ]
 [460.32 463.28]]


# Evaluating Results

In [25]:
from sklearn.metrics import r2_score
print("Coefficient of Determination of Multiple Regression model is : ", r2_score(y_test,y_pred_lrm))
print("Coefficient of Determination of Polynomial Regression model is : ", r2_score(y_test,y_pred_prm))
print("Coefficient of Determination of Decision Tree regression is : ", r2_score(y_test,y_pred_dtm))
print("Coefficient of Determination of Random Forest Regression model is : ", r2_score(y_test,y_pred_rfm))

Coefficient of Determination of Multiple Regression model is :  0.9325315554761302
Coefficient of Determination of Polynomial Regression model is :  0.9458192606428147
Coefficient of Determination of Decision Tree regression is :  0.9226091050550043
Coefficient of Determination of Random Forest Regression model is :  0.9615980699813017
